default_input_args: 
  start:
  distro:
  azure_warning:
  signing_key_path: test_config/enclave-key.pem
  attestation: done
  ssl_path: test_config/ssl
  runtime_args_text:
  runtime_variable_list:
  encrypted_files_path:
  signing_key_password:
  end:

test_redis_with_attestation:
  docker_image: redis redis:latest
  distro: 4

test_redis_with_test_attestation:
  docker_image: redis redis:latest
  attestation: test
  distro: 4

test_redis_with_attestation_local_image:
  docker_image: redis redis:7.0.0
  create_local_image: y
  distro: 4

test_redis_with_attestation_runtime_variables:
  docker_image: redis redis:latest
  runtime_variable_list: -e name="curator_app" -e version="1.2"
  distro: 4

test_redis_with_attestation_end_test_ssl_path:
  docker_image: redis redis:latest
  ssl_path: test_config/empty_ssl_folder
  expected_output_console: "One or more files does not exist at verifier/ssl/"
  end_test: attestation
  expected_screen: attestation_page
  distro: 4

test_redis_with_attestation_ssl_server_crt:
  docker_image: redis redis:latest
  ssl_path: test_config/ca_cert_folder
  end_test: attestation
  expected_output_console: "One or more files does not exist at verifier/ssl/"
  expected_screen: attestation_page
  distro: 4

test_redis_with_attestation_ssl_server_key:
  docker_image: redis redis:latest
  ssl_path: test_config/wo_server_key
  end_test: ssl_path
  expected_output_console: "One or more files does not exist at verifier/ssl/"
  expected_screen: attestation_page
  distro: 4

test_redis_with_attestation_wo_ssl:
  docker_image: redis redis:latest
  ssl_path: ''
  end_test: attestation
  expected_output_console: "One or more files does not exist at verifier/ssl/"
  expected_screen: attestation_page
  distro: 4

test_pytorch_with_attestation_no_encryption_key:
  docker_image: pytorch pytorch-encrypted:latest
  create_local_image: y
  encryption_key: ''
  encrypted_files_path: classes.txt:input.jpg:alexnet-pretrained.pt:result.txt
  expected_output_console: "Error:  file does not exist."
  end_test: encryption_key
  expected_screen: encryption_key_page

test_pytorch_with_attestation_encrypted_image:
  docker_image: pytorch pytorch-encrypted:latest
  create_local_image: y
  encryption_key: workloads/pytorch/base_image_helper/encryption_key
  encrypted_files_path: classes.txt:input.jpg:alexnet-pretrained.pt:result.txt
  distro: 1

test_pytorch_with_test_attestation:
  docker_image: pytorch pytorch-encrypted:latest
  create_local_image: y
  attestation: test
  encryption_key: workloads/pytorch/base_image_helper/encryption_key
  encrypted_files_path: classes.txt:input.jpg:alexnet-pretrained.pt:result.txt

test_pytorch_with_attestation_wrong_encrypted_list:
  docker_image: pytorch pytorch-encrypted:latest
  create_local_image: y
  encryption_key: workloads/pytorch/base_image_helper/encryption_key
  encrypted_files_path: input.jpg:alexnet-pretrained.pt:result.txt
  workload_result: "UnicodeDecodeError: 'utf-8' codec can't decode byte"

test_pytorch_with_attestation_invalid_encrypted_files:
  docker_image: pytorch pytorch-encrypted:latest
  create_local_image: y
  encryption_key: workloads/pytorch/base_image_helper/encryption_key
  encrypted_files_path: text-file
  workload_result: "_pickle.UnpicklingError: invalid load key, '\\x00'."

test_pytorch_with_attestation_encrypted_file_invalid_format:
  docker_image: pytorch pytorch-encrypted:latest
  create_local_image: y
  encryption_key: workloads/pytorch/base_image_helper/encryption_key
  encrypted_files_path: classes.txt;input.jpg;alexnet-pretrained.pt;result.txt
  workload_result: "_pickle.UnpicklingError: invalid load key, '\\x00'."

test_pytorch_with_attestation_invalid_encryption_key:
  docker_image: pytorch pytorch-encrypted:latest
  create_local_image: y
  encryption_key: test_config/invalid_wrap-key
  encrypted_files_path: classes.txt:input.jpg:alexnet-pretrained.pt:result.txt
  verifier_error: "[error] encryption key from /keys/invalid_wrap-key is not 16B in size"

test_bash_with_test_attestation:
  docker_image: bash bash-test:latest
  create_local_image: y
  runtime_variable_list: -e APP_NAME="Curated Apps"
  workload_result: "Curated Apps"
  attestation: test

test_bash_with_attestation:
  docker_image: bash bash-test:latest
  create_local_image: y
  runtime_variable_list: -e APP_NAME="Curated Apps"
  workload_result: "Curated Apps"

test_bash_attestation_without_verifier_image:
  docker_image: bash bash-test:latest
  create_local_image: y
  verifier_run: False
  workload_result: "secret_provision_start: Secret Provisioning could not connect to any of the servers specified in SECRET_PROVISION_SERVERS"

test_pytorch_with_test_option:
  docker_image: pytorch pytorch-encrypted:latest
  create_local_image: y
  test_option: y

test_sklearn_with_attestation:
  docker_image: sklearn sklearn-base:latest
  create_local_image: y
  distro: 4

test_sklearn_with_test_attestation:
  docker_image: sklearn sklearn-base:latest
  attestation: test
  create_local_image: y
  distro: 4
